### ISSUE TITLE
Can this be open sourced?

### ISSUE THREAD

**Issue by venezia** [travisghansen/docker-registry-curl#1]
I'd like to take it and convert it into a docker image that can be run on a gitlab-ci pipeline as part of cleanup.

LMK and thanks!

**Comment by travisghansen** [comment]
@venezia sure, any particular license you're hoping for?

**Comment by venezia** [comment]
Personally I like MIT or Apache 2.0 (Kubernetes is Apache 2.0)

**Comment by travisghansen** [comment]
@venezia I'm happy with MIT.  Interestingly enough, I actually bundle it with my gitlab-runner images for the same purpose.  I'd be happy to pull in a `Dockerfile` if you end up building one.

**Comment by venezia** [comment]
Great - sure add the MIT license and I'll fork this and give you a PR

**Comment by travisghansen** [comment]
@venezia done.

**Comment by venezia** [comment]
Thanks!
